services:
  - type: web
    name: animplay-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node dist/server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGO_URI
        value: mongodb+srv://animandy92_db_user:AnimAndy92%40gmail.com@animplaycluster.5ts9kam.mongodb.net/animplay_db?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: bqHgWikBaI6FjVJ7unfwtM894xDov1PG
      - key: GOOGLE_CLIENT_ID
        value: 17856885980-kggou5pigsibvspprc2aecc0l6an771e.apps.googleusercontent.com
