import { Router, Request, Response } from 'express';
import { Quiz, Question, Answer, nextId } from '../models';
import { authenticateToken } from './auth';

const router = Router();
const COLORS = ['red', 'blue', 'yellow', 'green'];

const AI_PROMPT = (topic: string, audience: string, count: number) =>
  `You are a quiz generator. Generate a ${count}-question multiple-choice quiz about "${topic}" for ${audience}. ` +
  `Return STRICTLY as a JSON array of objects. Each object must have: "question" (string), "options" (array of 4 strings), "correctAnswerIndex" (number 0-3). ` +
  `Keep questions clear, age-appropriate, and fun. No markdown, no code fences, only the raw JSON array.`;

const parseAiJson = (raw: string): any[] => {
  const match = raw.match(/\[[\s\S]*\]/);
  if (!match) throw new Error('No JSON array found in AI response');
  const parsed = JSON.parse(match[0]);
  if (!Array.isArray(parsed) || parsed.length === 0) throw new Error('Invalid quiz format');
  return parsed;
};

async function callAi(prompt: string): Promise<any[]> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('Server missing GEMINI_API_KEY');

  const body = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      temperature: 0.7,
      maxOutputTokens: 4096,
    },
  };

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 30000);

  let response: globalThis.Response;
  try {
    response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: controller.signal,
      }
    );
  } catch (err: any) {
    clearTimeout(timeoutId);
    if (err.name === 'AbortError') {
      throw new Error('AI request timed out');
    }
    throw new Error(`AI request failed: ${err.message}`);
  }
  clearTimeout(timeoutId);

  if (!response.ok) {
    let errorText = '';
    try {
      const errData = await response.json();
      errorText = (errData as any)?.error?.message || JSON.stringify(errData);
    } catch {
      errorText = await response.text();
    }
    throw new Error(`Gemini API error (${response.status}): ${errorText}`);
  }

  const data = await response.json() as any;
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    const finishReason = data.candidates?.[0]?.finishReason;
    if (finishReason === 'SAFETY' || finishReason === 'RECITATION') {
      throw new Error('AI response blocked by safety filters');
    }
    throw new Error('Empty AI response');
  }

  return parseAiJson(text);
}

router.post('/ai-generate', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const { topic, audience, count } = req.body;

  if (!topic || !topic.trim()) {
    return res.status(400).json({ error: 'Topic is required' });
  }
  if (!count || count < 1 || count > 20) {
    return res.status(400).json({ error: 'Count must be between 1 and 20' });
  }

  try {
    const questions = await callAi(AI_PROMPT(topic, audience || 'General', count));

    const quizId = await nextId('quizzes');
    const quiz = await Quiz.create({
      id: quizId,
      hostId,
      title: `${topic.trim()} Quiz`,
      description: `${count} questions generated by AI for ${audience || 'General'}`,
      status: 'draft',
      isPublic: false,
      category: 'general',
      playCount: 0,
      isFavorite: false,
      folderId: null,
      deletedAt: null,
    });

    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      const questionId = await nextId('questions');
      await Question.create({
        id: questionId,
        quizId: quizId,
        questionText: q.question,
        imageUrl: null,
        timerSeconds: 20,
        points: 1000,
        pointsMultiplier: 1.0,
        sortOrder: i,
        correctIndex: q.correctAnswerIndex ?? 0,
        questionType: 'multiple_choice',
      });

      const answers = Array.isArray(q.options)
        ? q.options.map((text: string, idx: number) => ({ text, color: COLORS[idx] || 'red' }))
        : [];

      for (let j = 0; j < answers.length; j++) {
        const answerId = await nextId('answers');
        await Answer.create({
          id: answerId,
          questionId,
          sortIndex: j,
          text: answers[j].text,
          color: answers[j].color,
        });
      }
    }

    res.json({ quiz: { id: quiz.id, title: quiz.title, description: quiz.description, question_count: questions.length } });
  } catch (err: any) {
    console.error('AI generation failed:', err);
    res.status(500).json({ error: err.message || 'AI generation failed' });
  }
});

router.get('/', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const tab = (req.query.tab as string) || 'recent';
  const folderId = req.query.folderId ? Number(req.query.folderId) : undefined;

  const filter: any = { hostId };
  if (tab === 'trash') {
    filter.deletedAt = { $ne: null };
  } else {
    filter.deletedAt = null;
    if (tab === 'drafts') filter.status = 'draft';
    else if (tab === 'favorites') filter.isFavorite = true;
    else if (tab === 'shared') {
      return res.json({ quizzes: [] });
    }
  }

  if (folderId) filter.folderId = folderId;

  let sort: any = { updatedAt: -1 };
  const quizzes = await Quiz.find(filter).sort(sort).lean();

  const result = [];
  for (const q of quizzes) {
    const questionCount = await Question.countDocuments({ quizId: q.id });
    result.push({ ...q, question_count: questionCount });
  }

  res.json({ quizzes: result });
});

router.post('/', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const { title, description, status, is_public } = req.body;

  if (!title) {
    return res.status(400).json({ error: 'Title is required' });
  }

  const id = await nextId('quizzes');
  const quiz = await Quiz.create({
    id,
    hostId,
    title,
    description: description || '',
    status: status || 'draft',
    isPublic: !!is_public,
    category: 'general',
    playCount: 0,
    isFavorite: false,
    folderId: null,
    deletedAt: null,
  });

  res.json({ quiz: { id: quiz.id, title, description } });
});

router.post('/:id/clone', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const sourceId = Number(req.params.id);

  const source = await Quiz.findOne({ id: sourceId, isPublic: true });
  if (!source) {
    return res.status(404).json({ error: 'Public quiz not found' });
  }

  const newQuizId = await nextId('quizzes');
  const newQuiz = await Quiz.create({
    id: newQuizId,
    hostId,
    title: `${source.title} (copy)`,
    description: source.description,
    isPublic: false,
    category: source.category || 'general',
    status: 'published',
    isFavorite: false,
    folderId: null,
    deletedAt: null,
  });

  const questions = await Question.find({ quizId: sourceId }).sort({ sortOrder: 1 }).lean();
  for (const q of questions) {
    const questionId = await nextId('questions');
    const newQ = await Question.create({
      id: questionId,
      quizId: newQuizId,
      questionText: q.questionText,
      imageUrl: q.imageUrl,
      timerSeconds: q.timerSeconds,
      points: q.points,
      pointsMultiplier: q.pointsMultiplier,
      sortOrder: q.sortOrder,
      correctIndex: q.correctIndex,
    });

    const answers = await Answer.find({ questionId: q.id }).sort({ sortIndex: 1 }).lean();
    for (const a of answers) {
      const answerId = await nextId('answers');
      await Answer.create({
        id: answerId,
        questionId,
        sortIndex: a.sortIndex,
        text: a.text,
        color: a.color,
      });
    }
  }

  await Quiz.updateOne({ id: sourceId }, { $inc: { playCount: 1 } });
  res.json({ quiz: { id: newQuizId, title: `${source.title} (copy)` } });
});

router.post('/:id/restore', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) return res.status(404).json({ error: 'Quiz not found' });

  await Quiz.updateOne({ id: quizId }, { $set: { deletedAt: null, updatedAt: new Date() } });
  res.json({ success: true });
});

router.get('/:id', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) {
    return res.status(404).json({ error: 'Quiz not found' });
  }

  const questions = await Question.find({ quizId }).sort({ sortOrder: 1 }).lean();
  for (const q of questions) {
    (q as any).answers = await Answer.find({ questionId: q.id }).sort({ sortIndex: 1 }).lean();
  }

  res.json({ quiz: { ...quiz.toObject(), questions } });
});

router.put('/:id', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);
  const { title, description, status, is_public, is_favorite, folderId } = req.body;

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) {
    return res.status(404).json({ error: 'Quiz not found' });
  }

  const update: any = { updatedAt: new Date() };
  if (title !== undefined) update.title = title;
  if (description !== undefined) update.description = description;
  if (status !== undefined) update.status = status;
  if (is_public !== undefined) update.isPublic = !!is_public;
  if (is_favorite !== undefined) update.isFavorite = !!is_favorite;
  if (folderId !== undefined) update.folderId = folderId ? Number(folderId) : null;

  await Quiz.updateOne({ id: quizId }, { $set: update });
  res.json({ success: true });
});

router.delete('/:id', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);
  const permanent = req.query.permanent === 'true';

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) {
    return res.status(404).json({ error: 'Quiz not found' });
  }

  if (permanent) {
    const qs = await Question.find({ quizId }).lean();
    for (const q of qs) {
      await Answer.deleteMany({ questionId: q.id });
    }
    await Question.deleteMany({ quizId });
    await Quiz.deleteOne({ id: quizId });
  } else {
    await Quiz.updateOne({ id: quizId }, { $set: { deletedAt: new Date(), updatedAt: new Date() } });
  }

  res.json({ success: true });
});

router.post('/:id/questions', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);
  const { question_text, timer_seconds, points, correct_index, answers, questionType } = req.body;

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) {
    return res.status(404).json({ error: 'Quiz not found' });
  }

  if (!question_text || !answers || answers.length < 2) {
    return res.status(400).json({ error: 'Question text and at least 2 answers are required' });
  }

  const last = await Question.findOne({ quizId }).sort({ sortOrder: -1 }).lean();
  const sortOrder = (last?.sortOrder ?? -1) + 1;

  const questionId = await nextId('questions');
  await Question.create({
    id: questionId,
    quizId,
    questionText: question_text,
    imageUrl: null,
    timerSeconds: timer_seconds || 20,
    points: points || 1000,
    pointsMultiplier: 1.0,
    sortOrder,
    correctIndex: correct_index ?? 0,
    questionType: questionType || 'multiple_choice',
  });

  for (let i = 0; i < answers.length; i++) {
    const answerId = await nextId('answers');
    await Answer.create({
      id: answerId,
      questionId,
      sortIndex: i,
      text: answers[i].text || answers[i],
      color: answers[i].color || COLORS[i] || 'red',
    });
  }

  await Quiz.updateOne({ id: quizId }, { $set: { updatedAt: new Date() } });
  res.json({ question: { id: questionId } });
});

router.put('/:id/questions/:qid', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);
  const questionId = Number(req.params.qid);
  const { question_text, timer_seconds, points, correct_index, answers, questionType } = req.body;

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) {
    return res.status(404).json({ error: 'Quiz not found' });
  }

  const update: any = {};
  if (question_text !== undefined) update.questionText = question_text;
  if (timer_seconds !== undefined) update.timerSeconds = timer_seconds;
  if (points !== undefined) update.points = points;
  if (correct_index !== undefined) update.correctIndex = correct_index;
  if (questionType !== undefined) update.questionType = questionType;

  if (Object.keys(update).length > 0) {
    await Question.updateOne({ id: questionId, quizId }, { $set: update });
  }

  if (answers && answers.length > 0) {
    await Answer.deleteMany({ questionId });
    for (let i = 0; i < answers.length; i++) {
      const answerId = await nextId('answers');
      await Answer.create({
        id: answerId,
        questionId,
        sortIndex: i,
        text: answers[i].text || answers[i],
        color: answers[i].color || COLORS[i] || 'red',
      });
    }
  }

  await Quiz.updateOne({ id: quizId }, { $set: { updatedAt: new Date() } });
  res.json({ success: true });
});

router.delete('/:id/questions/:qid', authenticateToken, async (req: Request, res: Response) => {
  const hostId = (req as any).hostId;
  const quizId = Number(req.params.id);
  const questionId = Number(req.params.qid);

  const quiz = await Quiz.findOne({ id: quizId, hostId });
  if (!quiz) {
    return res.status(404).json({ error: 'Quiz not found' });
  }

  await Question.deleteOne({ id: questionId, quizId });
  await Answer.deleteMany({ questionId });
  await Quiz.updateOne({ id: quizId }, { $set: { updatedAt: new Date() } });
  res.json({ success: true });
});

export default router;
